"""Redis Streams-based queue with consumer groups and dead-letter handling."""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

import redis.asyncio as aioredis

from src.infrastructure.telemetry import get_logger

logger = get_logger(__name__)

DLQ_SUFFIX = ":dlq"


@dataclass
class QueueMessage:
    """A message received from a Redis Stream."""

    stream: str
    msg_id: str
    payload: dict[str, Any]
    delivered_count: int = 1


class QueueManager:
    """
    Redis Streams-based async queue manager.

    Supports consumer groups, dead-letter queues, and health checking.
    """

    def __init__(self, redis_url: str, max_connections: int = 50) -> None:
        self._url = redis_url
        self._max_connections = max_connections
        self._client: aioredis.Redis | None = None

    async def connect(self) -> None:
        """Establish connection pool to Redis."""
        self._client = aioredis.from_url(
            self._url,
            max_connections=self._max_connections,
            decode_responses=True,
        )
        await self._client.ping()
        logger.info("queue.connected", url=self._url)

    async def close(self) -> None:
        """Close all connections."""
        if self._client:
            await self._client.aclose()
            self._client = None

    def _require_client(self) -> aioredis.Redis:
        if self._client is None:
            raise RuntimeError("QueueManager not connected. Call connect() first.")
        return self._client

    async def enqueue(
        self,
        stream: str,
        payload: dict[str, Any],
        msg_id: str | None = None,
        max_len: int = 10_000,
    ) -> str:
        """
        Add a message to a Redis Stream.

        Args:
            stream: Stream key name.
            payload: Serializable dict to enqueue.
            msg_id: Optional explicit message ID (default: auto-generated by Redis).
            max_len: Approximate max stream length (MAXLEN ~).

        Returns:
            Redis message ID string.
        """
        client = self._require_client()
        serialized = {k: json.dumps(v) if not isinstance(v, str) else v for k, v in payload.items()}
        result: str = await client.xadd(
            stream,
            serialized,
            id=msg_id or "*",
            maxlen=max_len,
            approximate=True,
        )
        return result

    async def consume(
        self,
        stream: str,
        group: str,
        consumer: str,
        count: int = 10,
        block_ms: int = 1000,
    ) -> list[QueueMessage]:
        """
        Read undelivered messages from a consumer group.

        Creates the group automatically if it doesn't exist.
        """
        client = self._require_client()
        await self.create_group(stream, group)

        try:
            raw = await client.xreadgroup(
                groupname=group,
                consumername=consumer,
                streams={stream: ">"},
                count=count,
                block=block_ms,
            )
        except aioredis.ResponseError as e:
            logger.warning("queue.consume_error", error=str(e))
            return []

        messages: list[QueueMessage] = []
        if raw:
            for _stream, entries in raw:
                for msg_id, fields in entries:
                    payload = {k: self._try_parse_json(v) for k, v in fields.items()}
                    messages.append(QueueMessage(stream=stream, msg_id=msg_id, payload=payload))
        return messages

    async def ack(self, stream: str, group: str, msg_id: str) -> None:
        """Acknowledge a message — removes it from the pending entries list."""
        client = self._require_client()
        await client.xack(stream, group, msg_id)

    async def create_group(self, stream: str, group: str) -> None:
        """Create a consumer group if it doesn't already exist."""
        client = self._require_client()
        try:
            await client.xgroup_create(stream, group, id="$", mkstream=True)
        except aioredis.ResponseError as e:
            if "BUSYGROUP" not in str(e):
                raise

    async def dead_letter(
        self, stream: str, msg_id: str, payload: dict[str, Any], reason: str
    ) -> None:
        """Move a failed message to the DLQ stream with failure metadata."""
        dlq_payload = {
            **payload,
            "original_stream": stream,
            "original_id": msg_id,
            "failure_reason": reason,
        }
        await self.enqueue(f"{stream}{DLQ_SUFFIX}", dlq_payload)
        logger.warning("queue.dead_lettered", stream=stream, msg_id=msg_id, reason=reason)

    async def health_check(self) -> bool:
        """Verify Redis connectivity via PING."""
        try:
            client = self._require_client()
            return await client.ping()
        except Exception:
            return False

    @staticmethod
    def _try_parse_json(value: str) -> Any:
        try:
            return json.loads(value)
        except (json.JSONDecodeError, TypeError):
            return value
